### ISSUE TITLE
multiple displays

### ISSUE THREAD

**Issue by zodiac1214** [gavinlyonsrepo/ER_OLEDM1_CH1115_RPI#1]
i have two displays but i can't make both of them working at the same time. it seems like whichever was initialized last will be able to display. every other display will just show white screen.

**Comment by gavinlyonsrepo** [comment]
Hi 

Which display is it?
Show your wiring and code please?

regards

**Comment by zodiac1214** [comment]
`// main.cpp

#include "DisplayManager.hpp"
#include <bcm2835.h>
#include <iostream>

void run();

int main()
{
    run();
    return 0;
}

void run()
{
    if (!bcm2835_init())
    {
        std::cout << "Error 1201: Problem with initializing bcm2835 library" << std::endl;
        return;
    }
    else
    {
        std::cout << "bcm2835 library version: " << bcm2835_version() << std::endl;
    }

    // Initialize multiple displays with different GPIO and SPI CE pins
    DisplayManager display1(1, 16, 24, 1, false, ST7735_TFT::TFT_Degrees_180, 128, 128); // RST=25, DC=23, SPI CE0
    DisplayManager display2(2, 25, 23, 0, false, ST7735_TFT::TFT_Degrees_180, 128, 128); // RST=27, DC=24, SPI CE1

    if (display1.setup() != 0)
        return;
    if (display2.setup() != 0)
        return;

    for (int i = 0; i < 100000; ++i) // Loop from 0 to 9
    {
        // Prepare a buffer to hold the formatted string
        char buffer[50]; // Adjust the size as needed

        // Use sprintf to format the string and store it in the buffer
        if (i % 360 < 10)
            sprintf(buffer, "00%d", i % 360);
        else if (i % 360 < 100)
            sprintf(buffer, "0%d", i % 360);
        else
            sprintf(buffer, "%d", i % 360);

        // Display on your device
        display1.display("HDG", buffer);

        display2.display("SPD", buffer);
    }

    display1.powerDown();
    display2.powerDown();

    bcm2835_close(); // Close the bcm2835 library
}`

st7735

my DisplayManager constructor: 
`DisplayManager::DisplayManager(int displayNumber, int8_t rst_pin, int8_t dc_pin, uint8_t spi_ce_pin, bool invert, ST7735_TFT::TFT_rotate_e rotate, uint16_t width, uint16_t height)
    : myTFT(), RST_TFT(rst_pin), DC_TFT(dc_pin), SPI_CE_PIN(spi_ce_pin), displayNumber(displayNumber), INVERT(invert), ROTATE(rotate), TFT_WIDTH(width), TFT_HEIGHT(height)
{
    // Constructor
}`

`void DisplayManager::display(const char *str1, const char *str2)
{
    myTFT.setCursor(5, 30);
    myTFT.setTextColor(0x07E0);
    myTFT.setFont(font_mega);
    myTFT.print(str1);

    // myTFT.fillRectangle(0, 60, 128, 128, RDLC_BLACK);
    myTFT.setCursor(5, 70);
    myTFT.setFont(font_mint);
    myTFT.setTextColor(0xFBE0);
    myTFT.print(str2);
    // myTFT.fillRectangle(0, 0, 160, 50, RDLC_YELLOW);
    // myTFT.fillRectangle(0, 50, 160, 78, RDLC_RED);
    // myTFT.fillRectangle(0, 0, 80, 160, RDLC_BLUE);
    // delayMilliSecRDL(1);
}`

**Comment by zodiac1214** [comment]
either of my display works but i can't have them together :( if i commented out display1, display2 works fine. if i commented out display2 code, display1 works fine....

**Comment by zodiac1214** [comment]
FWIW, i have the same wiring and that worked with some st7735 python library on my pi zero. i could get both display working (same SPI controller but different CS pin). and with this code, i can't get them working at the same time.

**Comment by gavinlyonsrepo** [comment]
Hi 

Can I see setup() code?

regards

**Comment by zodiac1214** [comment]
```
int8_t DisplayManager::setup()
{
    std::cout << "TFT Start for display " << displayNumber << std::endl;

    // Setup GPIO pins
    myTFT.TFTSetupGPIO(RST_TFT, DC_TFT);

    // Screen setup
    uint8_t OFFSET_COL = 0;
    uint8_t OFFSET_ROW = 0;

    myTFT.TFTInitScreenSize(OFFSET_COL, OFFSET_ROW, TFT_WIDTH, TFT_HEIGHT);

    // Initialize PCB type, SPI baud rate, and SPI CE pin
    uint32_t SCLK_FREQ = 10000000; // HW SPI freq in Hertz

    if (myTFT.TFTInitPCBType(myTFT.TFT_ST7735R_Red, SCLK_FREQ, SPI_CE_PIN) != rpiDisplay_Success)
    {
        return 3;
    }

    if (INVERT)
    {
        myTFT.TFTchangeInvertMode(true);
    }

    std::cout << "ST7735 library version: " << GetRDLibVersionNum() << std::endl;
    delayMilliSecRDL(50);
    myTFT.TFTsetRotation(ROTATE);
    myTFT.fillScreen(RDLC_BLACK);

    return 0;
}
```

**Comment by zodiac1214** [comment]
@gavinlyonsrepo or if you can provide an example maybe? i haven't touched c/c++ for 15yr+ now so i might have done something dumb here.

**Comment by gavinlyonsrepo** [comment]
Hi 

I think I see the problem. 

Note :: I never tested this with multiple displays just that the two different CEX(chip enable) pins worked.

The Hardware SPI settings (speed mode type and chip enable ) are only set by 
function **TFTSPIHWSettings()** internally  at start. They are not reset internally at each SPI transaction.

So if there are multiple devices with different settings the user must call (**TFTSPIHWSettings())** before each block of transaction to refresh settings for that device. 


So in pseudo code

//Display1.TFTSPIHWSettings() ;
//Display1.write();
//Display1.write();
//Display2.TFTSPIHWSettings() ;
/yDisplay2.write();
//Display2.write();
//Display1.TFTSPIHWSettings() ;
//Display1.write();


I will set up and test this later.  I wrote a note about this in function header but should have added it  to the readme.

**Comment by zodiac1214** [comment]
@gavinlyonsrepo that worked! ![PXL_20241024_150535351.MP.jpg](https://github.com/user-attachments/assets/2c4d564b-ce01-4a77-96b4-849cab9f9976)

**Comment by gavinlyonsrepo** [comment]
Good, I will add a note about multiple SPI devices to readme.
